# Generated by Django 6.1 on 2026-09-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_unique_user_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
    ]
