# Generated by Django 6.1 on 2026-09-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('reset', 'Password Reset')], default='signup', max_length=10),
        ),
    ]
