# Generated by Django 6.1 on 2026-09-12 16:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models._default_otp_expiry),
        ),
    ]
