# Generated by Django 6.1 on 2026-08-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='publishted_status',
            new_name='published_status',
        ),
    ]
